# Generated by Django 5.2.4 on 2025-07-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
