# Generated by Django 5.2.4 on 2025-07-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointment_user_alter_appointment_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
