# Generated by Django 5.2.4 on 2025-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_appointment_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
